/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;
using Konya_Hiermayer.Packages.Services.Filters;
using Microsoft.AspNetCore.Authentication;
using Microsoft.OpenApi.Models;
using AutoMapper;
using Konya_Hiermayer.Packages.BL.Interfaces;
using Konya_Hiermayer.Packages.BL;
using Konya_Hiermayer.Packages.Mapping;
using Konya_Hiermayer.Packages.DAL.SQL;
using Konya_Hiermayer.Packages.DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Konya_Hiermayer.Packages.ServiceAgents.Interfaces;
using Konya_Hiermayer.Packages.ServiceAgents;
using Microsoft.EntityFrameworkCore;
using FluentValidation.AspNetCore;
using FluentValidation;
using BLEntities = Konya_Hiermayer.Packages.BL.Entities;
using Konya_Hiermayer.Packages.BL.Validators;
using Konya_Hiermayer.Packages.BL.Entities.Validators;



namespace Konya_Hiermayer.Packages.Services
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        private readonly IWebHostEnvironment _hostingEnv;

        private IConfiguration Configuration { get; }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="env"></param>
        /// <param name="configuration"></param>
        public Startup(IWebHostEnvironment env, IConfiguration configuration)
        {
            _hostingEnv = env;
            Configuration = configuration;
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services
                .AddAutoMapper(typeof(MappingProfile))
                .AddMvc(options =>
                {
                    options.InputFormatters.RemoveType<Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter>();
                    options.OutputFormatters.RemoveType<Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter>();
                })
                .AddNewtonsoftJson(opts =>
                {
                    opts.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    opts.SerializerSettings.Converters.Add(new StringEnumConverter(new CamelCaseNamingStrategy()));
                })
                .AddXmlSerializerFormatters()
                .AddFluentValidation();
            services.AddTransient<IValidator<BLEntities.HopArrival>, HopArrivalValidator>();
            services.AddTransient<IValidator<BLEntities.Parcel>, ParcelValidator>();
            services.AddTransient<IValidator<BLEntities.Warehouse>, WarehouseValidator>();
            services.AddTransient<IValidator<BLEntities.Recipient>, RecipientValidator>();


            services.AddDbContext<DatabaseContext>(options =>
                    options.UseSqlServer(Configuration.GetConnectionString("LocalDbConnection"), x => x.UseNetTopologySuite()));
                


            services
                .AddSwaggerGen(c =>
                {
                    c.SwaggerDoc("1.20.2", new OpenApiInfo
                    {
                        Version = "1.20.2",
                        Title = "Parcel Logistics Service",
                        Description = "Parcel Logistics Service (ASP.NET Core 3.1)",
                        Contact = new OpenApiContact()
                        {
                           Name = "SKS",
                           Url = new Uri("http://www.technikum-wien.at/"),
                           Email = ""
                        }
                    });
                    c.CustomSchemaIds(type => type.FullName);
                    c.IncludeXmlComments($"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{_hostingEnv.ApplicationName}.xml");

                    // Include DataAnnotation attributes on Controller Action parameters as Swagger validation rules (e.g required, pattern, ..)
                    // Use [ValidateModelState] on Actions to actually validate it in C# as well!
                    c.OperationFilter<GeneratePathParamsValidationFilter>();
                });
            services.AddTransient<ILogisticsPartnerLogic, LogisticsPartnerLogic>();
            services.AddTransient<IRecipientLogic, RecipientLogic>();
            services.AddTransient<ISenderLogic, SenderLogic>();
            services.AddTransient<IStaffLogic, StaffLogic>();
            services.AddTransient<IWarehouseManagementLogic, WarehouseManagementLogic>();
            services.AddTransient<IWebhookLogic, WebhookLogic>();
            services.AddTransient<IHopRepository, HopRepository>();
            services.AddTransient<IParcelRepository, ParcelRepository>();
            services.AddTransient<IWarehouseRepository, WarehouseRepository>();
            services.AddTransient<IWebhookRepository, WebhookRepository>();
            services.AddTransient<IGeoCodingAgent, OSMGeoCodingAgent>();
            services.AddTransient<IRouteCalculator, RouteCalculator>();
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        /// <param name="loggerFactory"></param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseRouting();

            //TODO: Uncomment this if you need wwwroot folder
            // app.UseStaticFiles();

            app.UseAuthorization();

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                //TODO: Either use the SwaggerGen generated Swagger contract (generated from C# classes)
                c.SwaggerEndpoint("/swagger/1.20.2/swagger.json", "Parcel Logistics Service");

                //TODO: Or alternatively use the original Swagger contract that's included in the static files
                // c.SwaggerEndpoint("/swagger-original.json", "Parcel Logistics Service Original");
            });

            //TODO: Use Https Redirection
            // app.UseHttpsRedirection();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            // if (env.IsDevelopment())
            // {
            //     app.UseDeveloperExceptionPage();
            // }
            // else
            // {
            //     TODO: Enable production exception handling (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling)
            //     app.UseExceptionHandler("/Error");

            //     app.UseHsts();
            // }
        }
    }
}
